{
 "title": "Bosch CS5800/6800i & Buderus WLW176/186 Wärmepumpe (ems-esp + influxdb)",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "emsesp_host",
    "label": "Hostname or IP address of ems-esp gateway",
    "query": "${VAR_EMSESP_HOST}"
   },
   { "name": "api_key_ggc", "label": "API Key of Green Grid Compass", "query": "${VAR_API_KEY_GGC}" },
   { "name": "ref_heating_emissions", "label": "Reference Heating Emissions", "query": "${VAR_REF_HEATING_EMISSIONS}" }
  ]
 },
 "panels": [
  {
   "title": "Live",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "columns": [
      { "selector": "value", "text": "Außentemperatur", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/outdoortemp",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      {
       "selector": "value",
       "text": "Außenlufteintrittstemperatur (TL2)",
       "type": "number"
      }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/hptl2",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Aktuelle Brennerleistung", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/curburnpow",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "WP Kompressor", "type": "string" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/hpcompon",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "akt. Kompressorleistung", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/hpcurrpower",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Kompressoreingang (TR5)", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/hptr5",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Verdampfereingang (TR4)", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/hptr4",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Kompressoraktivität", "type": "string" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/hpactivity",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Kondensatortemperatur (TC3)", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/hptc3",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Kältemittel (flüssig) (TR3)", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/hptr3",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Durchfluss PC0", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/pc0flow",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Kältemittelvorlauf (TC1)", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/hptc1",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Kältemittelrücklauf (TC0)", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/hptc0",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Aktuelle Vorlauftemperatur", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/curflowtemp",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      {
       "selector": "value",
       "text": "WWK aktuelle externe Temperatur",
       "type": "number"
      }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/curtemp2",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      {
       "selector": "value",
       "text": "WWK aktuelle interne Temperatur",
       "type": "number"
      }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/curtemp",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Durchfluss PC1", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/pc1flow",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Zusatzheizerstatus", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/auxheaterlevel",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      {
       "selector": "value",
       "text": "HK1 berechnete Vorlauftemperatur",
       "type": "number"
      }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/thermostat/targetflowtemp",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  { "title": "Total (Detail)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Gesamtenergie",
   "type": "stat",
   "description": "### Elektrischer Energieeinsatz\nBisher eingesetzte elektrische Energie inkl. Kompressor, Pumpen, Elektronik, Kondensatwannenheizung, ...\n\n### Wärmeenergie\nBisher erzeugte Wärmeenergie. \nEnergieverlust beim Abtauen ist bereits abgezogen.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "columns": [
      { "selector": "value", "text": "nrgconstotal", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgconstotal",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "nrgsupptotal", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgsupptotal",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Gesamtenergie Heizen",
   "type": "stat",
   "description": "### Elektrischer Energieeinsatz (Heizen)\nBisher eingesetzte elektrische Energie für den Heizbetrieb inkl. Kompressor, Pumpen, Elektronik, Kondensatwannenheizung, ...\n\n### Wärmeenergie (Heizen)\nBisher erzeugte Wärmeenergie im Heizbetrieb. \nEnergieverlust beim Abtauen ist bereits abgezogen.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "columns": [
      {
       "selector": "value",
       "text": "Energieverbrauch Kompressor heizen",
       "type": "number"
      }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgconscompheating",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Gesamte Energieabgabe Heizen", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgsuppheating",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Gesamtenergie WW",
   "type": "stat",
   "description": "### Elektrischer Energieeinsatz (Warmwasser)\nBisher eingesetzter elektrischer Energie für die Warmwasseraufbereitung inkl. Kompressor, Pumpen, Elektronik, Kondensatwannenheizung, ...\n\n### Wärmeenergie (Warmwasser)\nBisher erzeugte Wärmeenergie für die Warmwasseraufbereitung. \nEnergieverlust beim Abtauen ist bereits abgezogen.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "columns": [
      {
       "selector": "value",
       "text": "Energieverbrauch Kompressor heizen",
       "type": "number"
      }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgconscomp",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Gesamte Energieabgabe Heizen", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgsupp",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Laufzeit & Starts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
   "targets": [
    {
     "columns": [
      { "selector": "value", "text": "Gesamtbetriebszeit Heizen", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/uptimecontrol",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Gesamtkompressorstarts", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/totalcompstarts",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Arbeitszahl",
   "type": "gauge",
   "description": "Die Arbeitszahl über die gesamte Laufzeit ist der Quotient aus bisher erzeugter Wärmeenergie und bisher eingesetzter elektrischer Energie.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "targets": [
    {
     "columns": [
      { "selector": "value", "text": "nrgconstotal", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgconstotal",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "nrgsupptotal", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgsupptotal",
     "url_options": { "data": "", "method": "GET" }
    },
    { "expression": "$nrgsupptotal / $nrgconstotal", "type": "math" }
   ]
  },
  {
   "title": "Arbeitszahl Heizen",
   "type": "gauge",
   "description": "Die Arbeitszahl über die gesamte Laufzeit ist der Quotient aus bisher erzeugter Wärmeenergie im Heizbetrieb und bisher eingesetzter elektrischer Energie im Heizbetrieb.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 14 },
   "targets": [
    {
     "columns": [
      { "selector": "value", "text": "nrgconscompheating", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgconscompheating",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "nrgsuppheating", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgsuppheating",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "expression": "$nrgsuppheating / $nrgconscompheating",
     "type": "math"
    }
   ]
  },
  {
   "title": "Arbeitszahl Warmwasser",
   "type": "gauge",
   "description": "Die Arbeitszahl über die gesamte Laufzeit ist der Quotient aus bisher erzeugter Wärmeenergie im Warmwasserbetrieb und bisher eingesetzter elektrischer Energie im Wasserwasserbetrieb.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 14 },
   "targets": [
    {
     "columns": [
      { "selector": "value", "text": "nrgconscompheating", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgsupp",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "nrgsuppheating", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgconscomp",
     "url_options": { "data": "", "method": "GET" }
    },
    { "expression": "$nrgsupp / $nrgconscomp", "type": "math" }
   ]
  },
  {
   "title": "⌀ Laufzeit / Start",
   "type": "gauge",
   "description": "Zur Schonung des Kompressors und für einen effizienten Betrieb sollte die Wärmepumpe möglichst kontinuierlich laufen mit möglichst wenig Takten.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expression": "$uptimecontrol / $totalcompstarts",
     "type": "math"
    }
   ]
  },
  {
   "title": "Heizen vs. Warmwasser",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "columns": [
      { "selector": "value", "text": "nrgconscompheating", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgconscompheating",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "nrgconscomp", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgconscomp",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "WP vs. Zuheizer",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "columns": [
      { "selector": "value", "text": "nrgconscomptotal", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgconscomptotal",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "auxelecheatnrgconstotal", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/auxelecheatnrgconstotal",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  { "title": "Intervall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Gesamtenergie (Intervall)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "alias": "Elektrischer Energieeinsatz",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "metertotal",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Wärmeenergieabgabe",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nrgtotal",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Arbeitszahl (Intervall)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expression": "$nrgtotal / $metertotal", "type": "math" }
   ]
  },
  {
   "title": "Heizen vs. WW (Intervall)",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Heizung",
     "measurement": "meterheat",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    },
    {
     "alias": "Warmwasser",
     "measurement": "dhw.meter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Eingesetzte elektrische Leistung vs. abgegebene Wärmeleistung (Intervall)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "alias": "Außentemperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "outdoortemp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Thermische Leistung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nrgtotal",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1h" ], "type": "derivative" },
       { "params": [ "3" ], "type": "moving_average" }
      ]
     ]
    },
    {
     "alias": "Elektrische Leistung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hpcurrpower",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "3" ], "type": "moving_average" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    },
    { "expression": "$nrgtotal / $hpcurrpower", "type": "math" },
    {
     "alias": "Modulation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "curburnpow",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Elektrischer Energieeinsatz: Heizung vs. Warmwasser (Intervall)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Außentemperatur",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "outdoortemp",
     "query": "SELECT mean(\"value\") FROM \"outdoortemp\" WHERE time > '${__from:date:YYYY-MM}-01' AND time <= '${__to:date}' GROUP BY time(1d) fill(null) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Warmwasser",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dhw.meter",
     "query": "SELECT spread(\"value\") FROM \"dhw.meter\" WHERE time > '${__from:date:YYYY-MM}-01' AND time < '${__to:date}' GROUP BY time(1d) fill(null) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    },
    {
     "alias": "Heizung",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "meterheat",
     "query": "SELECT spread(\"value\") FROM \"meterheat\" WHERE time > '${__from:date:YYYY-MM}-01' AND time < '${__to:date}' GROUP BY time(1d) fill(null) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Warmwassertemperatur (Intervall)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Warmwassertemperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "curtemp2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Nachhaltigkeit (Intervall)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Tägliche CO2 Emissionen der Wärmepumpe vs. Gasheizung (Intervall)",
   "type": "barchart",
   "description": "CO2 Emissionen der Wärmepumpe im Vergleich zu einer Gasheizung.\n\n### Wärmepumpe\nDie Emissionswerte des tagesdurchschnittlichen deutschen Strommixes (Lifecycle) werden über die API von [https://www.greengrid-compass.eu](https://www.greengrid-compass.eu) bezogen und mit der eingesetzten elektrischen Energie der Wärmepumpe an diesem Tag multipliziert. Hierfür muss ein API-Key auf [https://api-portal.eco2grid.com](https://api-portal.eco2grid.com/get-started) erstellt und in der Variablen `api_key_ggc` in den Dashboard-Einstellungen eingetragen werden.\n\n### Gasheizung\nDie Emissionen der Referenzgasheizung werden über die Grafana Variable `ref_heating_emissions = ${ref_heating_emissions} gCO2eq/kWh` definiert. Für die Berechnung der täglichen Emissionen werden die von der Wärmepumpe erzeugte Wärmeenergie mit den Emissionen der Gasheizung multipliziert.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    {
     "alias": "Täglicher Energieeinsatz",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "metertotal",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    },
    {
     "columns": [
      { "selector": "interval", "text": "Time", "type": "timestamp" },
      { "selector": "consumption_co2_intensity", "text": "CO2 Intensität", "type": "number" }
     ],
     "parser": "backend",
     "root_selector": "zone_data",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| jsonata \"$zip($[0].days,$[0].data)\"\n| project \"Time\"=todatetime(format_\"0\"), \"Renewable Share\"=\"1\"",
     "url": " https://eco2grid.com/green-grid-compass/co2intensity/co2/summary/daily",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": [
       { "key": "apikey", "value": "$api_key_ggc" },
       { "key": "start", "value": "${__from:date}" },
       { "key": "end", "value": "${__to:date}" },
       { "key": "emission_scope", "value": "lifecycle" },
       { "key": "zone_code", "value": "DE_LU" },
       { "key": "limit", "value": "365" }
      ]
     }
    },
    {
     "alias": "Gasheizung als Referenz",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nrgtotal",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "* $ref_heating_emissions" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Anteil erneuerbarer Energien und elektrischer Energieeinsatz pro Tag (Intervall)",
   "type": "timeseries",
   "description": "Der Anteil der erneuerbaren Energien des deutschen Stromverbrauchs wird von [https://www.greengrid-compass.eu](https://www.greengrid-compass.eu/) bezogen. Hierfür muss ein API-Key auf [https://api-portal.eco2grid.com](https://api-portal.eco2grid.com/get-started) erstellt und in der Variablen `api_key_ggc` in den Dashboard-Einstellungen eingetragen werden.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "columns": [
      { "selector": "interval", "text": "Time", "type": "timestamp" },
      { "selector": "consumption_renewable_ratio", "text": "Anteil erneuerbarer Energien", "type": "number" }
     ],
     "parser": "backend",
     "root_selector": "zone_data",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| jsonata \"$zip($[0].days,$[0].data)\"\n| project \"Time\"=todatetime(format_\"0\"), \"Renewable Share\"=\"1\"",
     "url": " https://eco2grid.com/green-grid-compass/co2intensity/co2/summary/daily",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": [
       { "key": "apikey", "value": "$api_key_ggc" },
       { "key": "start", "value": "${__from:date}" },
       { "key": "end", "value": "${__to:date}" },
       { "key": "emission_scope", "value": "lifecycle" },
       { "key": "zone_code", "value": "DE_LU" },
       { "key": "limit", "value": "365" }
      ]
     }
    },
    {
     "alias": "Täglicher Energieeinsatz",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "metertotal",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    },
    {
     "alias": "Täglicher Energieeinsatz (temporary)",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "metertotal",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    }
   ]
  }
 ]
}