{
 "title": "Bosch CS5800/6800i & Buderus WLW176/186 Wärmepumpe (ems-esp)",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "emsesp_host",
    "label": "Hostname or IP address of ems-esp gateway",
    "query": "${VAR_EMSESP_HOST}"
   }
  ]
 },
 "panels": [
  {
   "title": "Live",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "columns": [
      { "selector": "value", "text": "Außentemperatur", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/outdoortemp",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      {
       "selector": "value",
       "text": "Außenlufteintrittstemperatur (TL2)",
       "type": "number"
      }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/hptl2",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Aktuelle Brennerleistung", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/curburnpow",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "WP Kompressor", "type": "string" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/hpcompon",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "akt. Kompressorleistung", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/hpcurrpower",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Kompressoreingang (TR5)", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/hptr5",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Verdampfereingang (TR4)", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/hptr4",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Kompressoraktivität", "type": "string" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/hpactivity",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Kondensatortemperatur (TC3)", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/hptc3",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Kältemittel (flüssig) (TR3)", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/hptr3",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Durchfluss PC0", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/pc0flow",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Kältemittelvorlauf (TC1)", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/hptc1",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Kältemittelrücklauf (TC0)", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/hptc0",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Aktuelle Vorlauftemperatur", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/curflowtemp",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      {
       "selector": "value",
       "text": "WWK aktuelle externe Temperatur",
       "type": "number"
      }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/curtemp2",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      {
       "selector": "value",
       "text": "WWK aktuelle interne Temperatur",
       "type": "number"
      }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/curtemp",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Durchfluss PC1", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/pc1flow",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Zusatzheizerstatus", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/auxheaterlevel",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      {
       "selector": "value",
       "text": "HK1 berechnete Vorlauftemperatur",
       "type": "number"
      }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/thermostat/targetflowtemp",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  { "title": "Total (Detail)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Gesamtenergie",
   "type": "stat",
   "description": "### Elektrische Energie\nBisher eingesetzte elektrische Energie inkl. Kompressor, Pumpen, Elektronik, Kondensatwannenheizung, ...\n\n### Wärmeenergie\nBisher erzeugte Wärmeenergie. \nEnergieverlust beim Abtauen ist bereits abgezogen.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "columns": [
      { "selector": "value", "text": "nrgconstotal", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgconstotal",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "nrgsupptotal", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgsupptotal",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Gesamtenergie Heizen",
   "type": "stat",
   "description": "### Elektrische Energie (Heizen)\nBisher eingesetzte elektrische Energie für den Heizbetrieb inkl. Kompressor, Pumpen, Elektronik, Kondensatwannenheizung, ...\n\n### Wärmeenergie (Heizen)\nBisher erzeugte Wärmeenergie im Heizbetrieb. \nEnergieverlust beim Abtauen ist bereits abgezogen.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "columns": [
      {
       "selector": "value",
       "text": "Energieverbrauch Kompressor heizen",
       "type": "number"
      }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgconscompheating",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Gesamte Energieabgabe Heizen", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgsuppheating",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Gesamtenergie WW",
   "type": "stat",
   "description": "### Elektrische Energie (Warmwasser)\nBisher eingesetzter elektrischer Energie für die Warmwasseraufbereitung inkl. Kompressor, Pumpen, Elektronik, Kondensatwannenheizung, ...\n\n### Wärmeenergie (Warmwasser)\nBisher erzeugte Wärmeenergie für die Warmwasseraufbereitung. \nEnergieverlust beim Abtauen ist bereits abgezogen.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "columns": [
      {
       "selector": "value",
       "text": "Energieverbrauch Kompressor heizen",
       "type": "number"
      }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgconscomp",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Gesamte Energieabgabe Heizen", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgsupp",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Laufzeit & Starts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
   "targets": [
    {
     "columns": [
      { "selector": "value", "text": "Gesamtbetriebszeit Heizen", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/uptimecontrol",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "Gesamtkompressorstarts", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/totalcompstarts",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Arbeitszahl",
   "type": "gauge",
   "description": "Die Arbeitszahl über die gesamte Laufzeit ist der Quotient aus bisher erzeugter Wärmeenergie und bisher eingesetzter elektrischer Energie.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "targets": [
    {
     "columns": [
      { "selector": "value", "text": "nrgconstotal", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgconstotal",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "nrgsupptotal", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgsupptotal",
     "url_options": { "data": "", "method": "GET" }
    },
    { "expression": "$nrgsupptotal / $nrgconstotal", "type": "math" }
   ]
  },
  {
   "title": "Arbeitszahl Heizen",
   "type": "gauge",
   "description": "Die Arbeitszahl über die gesamte Laufzeit ist der Quotient aus bisher erzeugter Wärmeenergie im Heizbetrieb und bisher eingesetzter elektrischer Energie im Heizbetrieb.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 14 },
   "targets": [
    {
     "columns": [
      { "selector": "value", "text": "nrgconscompheating", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgconscompheating",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "nrgsuppheating", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgsuppheating",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "expression": "$nrgsuppheating / $nrgconscompheating",
     "type": "math"
    }
   ]
  },
  {
   "title": "Arbeitszahl Warmwasser",
   "type": "gauge",
   "description": "Die Arbeitszahl über die gesamte Laufzeit ist der Quotient aus bisher erzeugter Wärmeenergie im Warmwasserbetrieb und bisher eingesetzter elektrischer Energie im Wasserwasserbetrieb.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 14 },
   "targets": [
    {
     "columns": [
      { "selector": "value", "text": "nrgconscompheating", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgsupp",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "nrgsuppheating", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgconscomp",
     "url_options": { "data": "", "method": "GET" }
    },
    { "expression": "$nrgsupp / $nrgconscomp", "type": "math" }
   ]
  },
  {
   "title": "⌀ Laufzeit / Start",
   "type": "gauge",
   "description": "Zur Schonung des Kompressors und für einen effizienten Betrieb sollte die Wärmepumpe möglichst kontinuierlich laufen mit möglichst wenig Takten.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expression": "$uptimecontrol / $totalcompstarts",
     "type": "math"
    }
   ]
  },
  {
   "title": "Heizen vs. Warmwasser",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "columns": [
      { "selector": "value", "text": "nrgconscompheating", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgconscompheating",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "nrgconscomp", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgconscomp",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "WP vs. Zuheizer",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "columns": [
      { "selector": "value", "text": "nrgconscomptotal", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/nrgconscomptotal",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "value", "text": "auxelecheatnrgconstotal", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://${emsesp_host}/api/boiler/auxelecheatnrgconstotal",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}